# Generated by Django 5.2.7 on 2026-04-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_Manage', '0003_alter_order_client_alter_order_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='type',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='unit',
        ),
    ]
