# Generated by Django 5.2.7 on 2026-04-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='producttype',
            name='unit',
            field=models.CharField(choices=[('litre', 'Litre'), ('kg', 'Kilo Gram')], db_index=True, max_length=20, null=True),
        ),
    ]
