# Generated by Django 5.2.7 on 2026-04-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_product_unit_producttype_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='unit',
            field=models.CharField(choices=[('litre', 'Litre'), ('kg', 'Kilo Gram')], db_index=True, max_length=20),
        ),
    ]
