# Generated by Django 5.2.7 on 2026-04-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_Manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='states',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='states',
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('invoiced', 'Invoiced')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('plus', 'Plus'), ('minus', 'Minus')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('plus', 'Plus'), ('minus', 'Minus')], default='normal', max_length=20),
        ),
    ]
