# Generated by Django 5.2.7 on 2026-04-08 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_Manage', '0004_remove_orderproduct_type_remove_orderproduct_unit'),
        ('user', '0003_rename_lastname_client_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.client'),
        ),
    ]
