# Generated by Django 5.2.7 on 2026-04-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('plus', 'Plus'), ('minus', 'Minus')], max_length=20),
        ),
    ]
